name: release
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/easybangumi.jks

      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleRelease
        env:
          BUGLY_APPID: ${{ secrets.BUGLY_APPID || 'release' }}
          KEYSTORE_FILE: easybangumi.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Get Version
        run: |
          echo "BANGUMI_VERSION=$(jq -r '.elements[0].versionName' app/build/outputs/apk/release/output-metadata.json)" >> $GITHUB_ENV

      - name: Rename APK
        run: mv app/build/outputs/apk/release/*.apk easybangumi-${{ env.BANGUMI_VERSION }}.apk

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: easybangumi-${{ env.BANGUMI_VERSION }}.apk
          path: easybangumi-${{ env.BANGUMI_VERSION }}.apk
          compression-level: 0

      - name: Release
        run: gh release create -d ${{ env.BANGUMI_VERSION }} easybangumi-${{ env.BANGUMI_VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
